service: sample

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: local

plugins:
  - serverless-localstack
  
package:
  individually: true
  custom:
    localstack:
      debug: true
      edgePort: 4566
      autostart: false
      stages: [local]
      lambda:
        mountCode: true

functions:
  main:
    handler: lambda_function.lambda_handler